sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'dummy@example.org'
after_script: NODE_ENV=test grunt sendCoverallsInfo
env:
  global:
    - secure: EZYmqw5NpT8+jkr2m94e5R2LfT7v9fXvt9VjA4n2VM7smYh8N/dlmjHlA9GKs1jagcZsUD4RVVkpLzatbFgjofatt5RhyX/5OxSyN9PsfvqslZ0ppvp2BjlU6/l/AHogiMT+K/8iK7ebGUG71QogivS3sOLCN10O6KFB9aIGPM5Iiz6Q48x0DATdr/0zmno4rqI2HMBQDw2AOHGBGNSRk4F/8QvqgMkZ3v490KxnwpagkfAmHzu37JyWrVLpPboyVpF/N6e4DzOyy5vcStkmaG2ohkx0r61ZLbWQcM/diqIGV127L9UeWYMWEVGi5qwGlBGfS4V94PCZkmA0oG1NJwHe86ibX3hblJEJ8uICkY62CALeRN0My/A0LxpYqoEH31W7HXl16EHFo2FKdMtltt1KYOpl3JflKhuT3cV2DyRFS4m1a4F5/9fkRKLQ/Lj1C4tYPysa+oz54C2mWZl3FxKgBkRZ2EmXdFH5vlSH7+/1VciylvFzF/Dqm6ozjuMZfOs2GZjRQBSQE0TPyUBDLD++0JmytWHnw9F5CcIKIyndp6d3GlGzdskXOymE2Q9HHjXXAVQ0jk74FMIdkkf3jiSQSBTe34giBSm98bRud/1YMLhNGttt7+hbG7HXbC5ROEVceFl9/vhqld1SNB0nMlEYKYVjOdOk1eqNR+dsOfI=
